sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer install -n

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcpd --min-tokens 10 source
  - vendor/bin/phpcs --standard=PSR2 --extensions=php source
  - vendor/bin/phpunit --coverage-text